try a fix on console

diff --git a/mctl b/mctl
--- a/mctl
+++ b/mctl
@@ -52,7 +52,7 @@ check_if_running(){
 
 function start(){
   if check_if_running; then
-    echo -e "${RED}[ERROR]${RESET} tmux session is already running"
+    echo -e "[ ${RED}✕${RESET} ] tmux session is already running"
     echo -e "check that the session is not running empty with : tmux -S ${TMUX_SOCKET_PATH} a -t ${TMUX_SESSION_NAME}"
     exit 1
   fi
@@ -62,14 +62,14 @@ function start(){
 
 function stop(){
   if ! tmux -S $TMUX_SOCKET_PATH ls | grep $TMUX_SESSION_NAME > /dev/null 2>&1; then
-    echo -e "${RED}[ERROR]${RESET} cannot stop server, server is offline"
+    echo -e "[ ${RED}✕${RESET} ] cannot stop server, server is offline"
     exit 1
   fi
   if [ $ISHARD == false ]; then
     tmux -S $TMUX_SOCKET_PATH send-keys -t $TMUX_SESSION_NAME 'say Arret du serveur dans 30 secondes' Enter
     echo -e "[LOG] sleeping for 30s..."
     progress-bar 30
-    echo -e "done"
+    echo -e "[ ${GREEN}✔${RESET} ] - done"
   fi
   tmux -S $TMUX_SOCKET_PATH send-keys -t $TMUX_SESSION_NAME 'say Arret du serveur !' Enter
   sleep 3
@@ -80,12 +80,18 @@ function stop(){
 
 function console(){
   if ! check_if_running; then
-    echo -e "${RED}[ERROR]${RESET} server is not running"
+    echo -e "[ ${RED}✕${RESET} ] server is not running"
     exit 1
   fi
+  user_input(){
+    read -p -r "> " input
+    case $input in
+      exit | quit | stop ) exit 0 ;;
+      * ) tmux -S $TMUX_SOCKET_PATH send-keys -t $TMUX_SESSION_NAME "${input}" Enter
+    esac
+  }
+  trap user_input SIGINT
   tail -f "$SERVER_PATH/logs/latest.log"
-  read -p -r "> " input
-  tmux -S $TMUX_SOCKET_PATH send-keys -t $TMUX_SESSION_NAME "${input}" Enter
   exit 0
 }
 
@@ -132,7 +138,7 @@ function version(){
 }
 
 if [ $# -gt 2 ]; then
-  echo -e "[ERROR] too many arguments."
+  echo -e "[ ${RED}✕${RESET} ] too many arguments."
   help
 fi
 
@@ -144,10 +150,10 @@ for i in "$@"; do case $i in
   console ) console ;;
   -h | --help ) help ;;
   -f | --force ) ISHARD=true ;;
-  * ) echo -e "${RED}[ERROR]${RESET} Invalid argument" && help ;;
+  * ) echo -e "[ ${RED}✕${RESET} ] Invalid argument" && help ;;
 esac
 done
 
-echo -e "${RED}[ERROR]${RESET} program require a command"
+echo -e "[ ${RED}✕${RESET} ] program require a command"
 help
 
